#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    export PLAYWRIGHT_BROWSERS_PATH="${PLAYWRIGHT_BROWSERS_PATH:-/opt/playwright}"
    mkdir -p "$PLAYWRIGHT_BROWSERS_PATH"
    chown sail:"$(id -gn sail)" "$PLAYWRIGHT_BROWSERS_PATH"
    if [ -f /var/www/html/node_modules/playwright/package.json ]; then
        gosu sail node /var/www/html/scripts/ensure-report-browser.mjs || exit 1
    fi
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
